"""Report rendering entry points."""

from repolens.report.gate import ReportGateOpen
from repolens.report.main import (
    COLUMNS,
    DEFAULT_LEGAL_TEXT,
    DOCX_SKIPPED_NOTICE,
    DisclosureRow,
    ReportAppendixSummary,
    ReportResult,
    aggregate_rows,
    collect_resolved_records,
    render_csv,
    render_html,
    render_main_report,
    render_markdown,
    select_main_report_rows,
)
from repolens.report.presentation import (
    DATA_LIMITATION_NOTE,
    PRESENTATION_COLUMNS,
    PresentationResult,
    PresentationRow,
    presentation_rows_from_disclosure,
    render_presentation_artifacts,
    render_presentation_csv,
    render_presentation_docx,
    render_presentation_html,
    render_presentation_markdown,
)
from repolens.report.selection import (
    ReportHeader,
    ReportSelection,
    report_header_if_configured,
)

__all__ = [
    "COLUMNS",
    "DATA_LIMITATION_NOTE",
    "DEFAULT_LEGAL_TEXT",
    "DOCX_SKIPPED_NOTICE",
    "PRESENTATION_COLUMNS",
    "DisclosureRow",
    "PresentationResult",
    "PresentationRow",
    "ReportGateOpen",
    "ReportHeader",
    "ReportAppendixSummary",
    "ReportResult",
    "ReportSelection",
    "aggregate_rows",
    "collect_resolved_records",
    "render_csv",
    "render_html",
    "render_main_report",
    "render_markdown",
    "select_main_report_rows",
    "render_presentation_artifacts",
    "render_presentation_csv",
    "render_presentation_docx",
    "render_presentation_html",
    "render_presentation_markdown",
    "presentation_rows_from_disclosure",
    "report_header_if_configured",
]
