"""Render the R1 main disclosure report from resolved records."""

from __future__ import annotations

import sys
from collections import Counter
from collections.abc import Iterable, Sequence
from dataclasses import dataclass, field
from html import escape as html_escape
from pathlib import Path
from typing import Any, TextIO
from urllib.parse import quote, urlparse

from repolens.config import Config
from repolens.data import store
from repolens.data.limits import max_bytes_for
from repolens.discovery.taxonomy import DEFAULT_CATEGORY
from repolens.exit_codes import InputError
from repolens.report.categories import RoutedRecord, build_category_index, route_occurrences
from repolens.report.dependency_boundaries import (
    build_dependency_boundary_summary,
    render_dependency_boundaries_markdown,
    write_dependency_boundary_artifacts,
)
from repolens.report.docx import render_docx
from repolens.report.gate import ReportGateOpen, run_report_gate
from repolens.report.selection import (
    ReportHeader,
    report_header_if_configured,
    report_selection_from_config,
)
from repolens.resolve.descriptions import brief_description
from repolens.scan.inputs import load_discover_approved_repo_refs
from repolens.security.redaction import redact_tokens
from repolens.security.sanitize import (
    markdown_link,
    render_code_span,
    sanitize_markdown,
    serialize_csv_rows,
)

COLUMNS = (
    "name",
    "spdx_id",
    "version",
    "source_url",
    "modified?",
    "origin",
    "scope",
    "distribution",
    "found_in",
    "evidence_source_layer",
    "coverage_gaps",
)
_HTML_COLUMN_WIDTHS = (10, 7, 7, 25, 6, 9, 6, 7, 8, 7, 8)

_NONE = "none"
_UNKNOWN = "UNKNOWN"

DEFAULT_LEGAL_TEXT = "Generated by RepoLens — not legal advice; verify before distribution."
DOCX_SKIPPED_NOTICE = (
    "docx files skipped (no report.header); md/csv/html contain all the data — "
    "add report.header config or run interactively to generate it."
)
DECLARED_UNPINNED_STATUS = "declared-unpinned"


@dataclass(frozen=True)
class DisclosureRow:
    """One deduplicated report row."""

    name: str
    spdx_id: str
    versions: tuple[str, ...]
    source_urls: tuple[str, ...]
    modified: tuple[str, ...]
    origins: tuple[str, ...]
    scopes: tuple[str, ...]
    distributions: tuple[str, ...]
    found_in: tuple[str, ...]
    evidence_source_layers: tuple[str, ...]
    coverage_gaps: tuple[str, ...]
    descriptions: tuple[str, ...] = ()


@dataclass(frozen=True)
class ReportAppendixSummary:
    """Summary metadata for one appendix label."""

    label: str
    row_count: int
    markdown_path: Path
    csv_path: Path
    coverage_gaps: tuple[tuple[str, int], ...] = ()


@dataclass(frozen=True)
class ReportResult:
    """Paths and summary for emitted report artifacts.

    ``docx_path`` is ``None`` and ``docx_skipped`` is ``True`` when the docx was
    intentionally skipped (no ``report.header`` config in a non-interactive run).
    """

    markdown_path: Path
    csv_path: Path
    html_path: Path
    row_count: int
    file_gaps: tuple[str, ...]
    docx_path: Path | None = None
    appendix_paths: tuple[Path, ...] = ()
    dependency_boundary_paths: tuple[Path, ...] = ()
    appendices: tuple[ReportAppendixSummary, ...] = ()
    coverage_gaps: tuple[tuple[str, int], ...] = ()
    docx_skipped: bool = False
    presentation_markdown_path: Path | None = None
    presentation_csv_path: Path | None = None
    presentation_html_path: Path | None = None
    presentation_docx_path: Path | None = None
    presentation_docx_skipped: bool = False


@dataclass
class _DisclosureAccumulator:
    name: str
    spdx_id: str
    versions: set[str] = field(default_factory=set)
    source_urls: set[str] = field(default_factory=set)
    descriptions: set[str] = field(default_factory=set)
    modified: set[str] = field(default_factory=set)
    origins: set[str] = field(default_factory=set)
    scopes: set[str] = field(default_factory=set)
    distributions: set[str] = field(default_factory=set)
    found_in: set[str] = field(default_factory=set)
    evidence_source_layers: set[str] = field(default_factory=set)
    coverage_gaps: set[str] = field(default_factory=set)

    def to_row(self) -> DisclosureRow:
        gaps = set(self.coverage_gaps)
        if len(self.origins) > 1:
            gaps.add("mixed_origin")
        if len(self.scopes) > 1:
            gaps.add("mixed_scope")
        if len(self.distributions) > 1:
            gaps.add("mixed_distribution")
        if len(self.modified) > 1:
            gaps.add("mixed_modified")
        return DisclosureRow(
            name=self.name,
            spdx_id=self.spdx_id,
            versions=_sorted_values(self.versions),
            source_urls=_sorted_values(self.source_urls),
            descriptions=_sorted_values(self.descriptions),
            modified=_sorted_values(self.modified),
            origins=_sorted_values(self.origins),
            scopes=_sorted_values(self.scopes),
            distributions=_sorted_values(self.distributions),
            found_in=_sorted_values(self.found_in),
            evidence_source_layers=_sorted_values(self.evidence_source_layers),
            coverage_gaps=_sorted_values(gaps),
        )


def render_main_report(
    work_root: Path,
    out_dir: Path | None = None,
    config: Config | None = None,
    *,
    interactive: bool = False,
    owner: str | None = None,
    input_stream: TextIO | None = None,
    output_stream: TextIO | None = None,
) -> ReportResult:
    """Render main and appendix report artifacts from resolved occurrences.

    The md/csv/appendix data always renders and never depends on header config.
    The docx cover is produced when ``report.header`` config is present, prompted
    inline when ``interactive`` and no header is configured, or skipped (with a
    one-line notice on ``output_stream``) when neither applies.
    """

    root = Path(work_root)
    output_dir = Path(out_dir) if out_dir is not None else root / "reports"
    gate = run_report_gate(root)
    if not gate.clear:
        raise ReportGateOpen(gate.message)

    split, file_gaps = _split_report_records(root, config)
    rows = aggregate_rows(split.main_records)
    dependency_boundary_summary = build_dependency_boundary_summary(root)

    csv_text = redact_tokens(render_csv(rows))
    markdown_text = render_markdown(rows, file_gaps)
    html_text = render_html(rows, file_gaps)
    if dependency_boundary_summary is not None:
        markdown_text = (
            markdown_text.rstrip()
            + "\n\n"
            + render_dependency_boundaries_markdown(
                dependency_boundary_summary,
                title="Dependency Boundaries",
                heading_level=2,
            )
        )
    markdown_text = redact_tokens(markdown_text)
    html_text = redact_tokens(html_text)

    csv_path = output_dir / "report.main.csv"
    markdown_path = output_dir / "report.main.md"
    html_path = output_dir / "report.main.html"
    store.atomic_write_bytes(csv_path, csv_text.encode("utf-8"))
    store.atomic_write_bytes(markdown_path, markdown_text.encode("utf-8"))
    store.atomic_write_bytes(html_path, html_text.encode("utf-8"))

    appendix_paths: list[Path] = []
    dependency_boundary_paths: tuple[Path, ...] = ()
    if dependency_boundary_summary is not None:
        dependency_boundary_paths = write_dependency_boundary_artifacts(
            output_dir,
            dependency_boundary_summary,
        )
    appendices: list[ReportAppendixSummary] = []
    for label, routed_records in split.appendix_records_by_label.items():
        appendix_rows = aggregate_rows(routed_records)
        stem = f"report.appendix.{quote(label, safe='')}"
        appendix_csv_path = output_dir / f"{stem}.csv"
        appendix_markdown_path = output_dir / f"{stem}.md"
        appendix_csv = redact_tokens(render_csv(appendix_rows))
        appendix_markdown = redact_tokens(
            render_markdown(
                appendix_rows,
                (),
                title=f"RepoLens Appendix: {label}",
            )
        )
        store.atomic_write_bytes(appendix_csv_path, appendix_csv.encode("utf-8"))
        store.atomic_write_bytes(appendix_markdown_path, appendix_markdown.encode("utf-8"))
        appendix_paths.extend((appendix_markdown_path, appendix_csv_path))
        appendices.append(
            ReportAppendixSummary(
                label=label,
                row_count=len(appendix_rows),
                markdown_path=appendix_markdown_path,
                csv_path=appendix_csv_path,
                coverage_gaps=_coverage_gap_counts(appendix_rows),
            )
        )

    # Presentation-only docx: config → prompt (TTY) → skip (non-TTY / no owner).
    out_stream = output_stream if output_stream is not None else sys.stderr
    header = report_header_if_configured(config)
    if header is None and interactive:
        in_stream = input_stream if input_stream is not None else sys.stdin
        header = _prompt_for_header(owner, in_stream, out_stream)

    docx_path: Path | None = None
    docx_skipped = False
    if header is not None:
        docx_bytes = render_docx(header, COLUMNS, rows)
        docx_path = output_dir / "report.main.docx"
        store.atomic_write_bytes(docx_path, docx_bytes)
    else:
        print(DOCX_SKIPPED_NOTICE, file=out_stream)
        docx_skipped = True

    from repolens.report.presentation import render_presentation_artifacts
    from repolens.report.review import load_presentation_text, load_review_state

    review_state = load_review_state(root)
    presentation_text = load_presentation_text(root)
    presentation = render_presentation_artifacts(
        rows,
        output_dir,
        header=header,
        review_state=review_state,
        title=presentation_text.header,
        preamble=presentation_text.preamble,
    )

    return ReportResult(
        markdown_path=markdown_path,
        csv_path=csv_path,
        html_path=html_path,
        docx_path=docx_path,
        row_count=len(rows),
        file_gaps=tuple(file_gaps),
        appendix_paths=tuple(appendix_paths),
        dependency_boundary_paths=dependency_boundary_paths,
        appendices=tuple(appendices),
        coverage_gaps=_coverage_gap_counts(rows, file_gaps),
        docx_skipped=docx_skipped,
        presentation_markdown_path=presentation.markdown_path,
        presentation_csv_path=presentation.csv_path,
        presentation_html_path=presentation.html_path,
        presentation_docx_path=presentation.docx_path,
        presentation_docx_skipped=presentation.docx_skipped,
    )


def _prompt_for_header(
    owner: str | None,
    in_stream: TextIO,
    out_stream: TextIO,
) -> ReportHeader | None:
    """Prompt for the docx header. Returns ``None`` to skip (EOF with no owner)."""

    print(
        "No report header configured. Let's add one for the shareable .docx\n"
        "(press Enter to accept the default; this only affects the docx cover, not the data).",
        file=out_stream,
    )
    org_name = _prompt_org_name(owner, in_stream, out_stream)
    if org_name is None:
        return None
    legal_text = _prompt_legal_text(in_stream, out_stream)
    return ReportHeader(org_name=org_name, legal_text=legal_text)


def _prompt_org_name(
    owner: str | None,
    in_stream: TextIO,
    out_stream: TextIO,
) -> str | None:
    """Read a non-empty org name, defaulting to ``owner``.

    Returns ``None`` only when the stream hits EOF with no usable owner default —
    the caller then skips the docx rather than render a blank cover.
    """

    default = owner.strip() if owner and owner.strip() else None
    label = f"  Organization name [{default}]: " if default else "  Organization name: "
    while True:
        print(label, end="", file=out_stream, flush=True)
        line = in_stream.readline()
        if line == "":  # EOF
            return default
        value = line.strip()
        if value:
            return value
        if default:
            return default
        # Empty input with no owner default: re-prompt for a required org name.


def _prompt_legal_text(in_stream: TextIO, out_stream: TextIO) -> str:
    print(
        f"  Legal / disclaimer line [{DEFAULT_LEGAL_TEXT}]: ",
        end="",
        file=out_stream,
        flush=True,
    )
    line = in_stream.readline()
    if line == "":  # EOF
        return DEFAULT_LEGAL_TEXT
    return line.strip() or DEFAULT_LEGAL_TEXT


def collect_resolved_records(
    work_root: Path,
    active_repo_refs: Sequence[str] | None = None,
) -> tuple[list[dict[str, Any]], list[str]]:
    """Collect records from ``work/*/resolved.ndjson`` using the store boundary."""

    work_dir = Path(work_root) / "work"
    if active_repo_refs is None and not work_dir.is_dir():
        raise InputError("report requires work/<repo>/resolved.ndjson input")

    if active_repo_refs is None:
        repo_dirs = sorted(
            (path for path in work_dir.iterdir() if path.is_dir()), key=_path_sort_key
        )
    else:
        repo_dirs = [store.repo_dir(work_root, repo_ref) for repo_ref in active_repo_refs]

    if not repo_dirs:
        raise InputError("report requires at least one work/<repo>/resolved.ndjson input")

    records: list[dict[str, Any]] = []
    file_gaps: list[str] = []
    missing_resolved: list[str] = []
    resolved_seen = False
    for repo_dir in repo_dirs:
        resolved_path = repo_dir / "resolved.ndjson"
        if not resolved_path.exists():
            if active_repo_refs is not None or (repo_dir / "sbom.syft.json").exists():
                missing_resolved.append(str(resolved_path.relative_to(work_root)))
            continue

        resolved_seen = True
        before_count = len(records)
        records.extend(store.iter_resolved(resolved_path))
        if len(records) == before_count:
            file_gaps.append(f"empty_resolved_file: {resolved_path.relative_to(work_root)}")

    if missing_resolved:
        raise InputError(f"incomplete R1 input: missing {', '.join(missing_resolved)}")
    if not resolved_seen:
        raise InputError("report found no work/<repo>/resolved.ndjson input")
    return records, sorted(file_gaps, key=lambda value: (value.casefold(), value))


def _exclude_rejected_shortlist_records(
    work_root: Path,
    records: Sequence[dict[str, Any]],
) -> list[dict[str, Any]]:
    rejected_refs = _rejected_shortlist_component_refs(work_root)
    if not rejected_refs:
        return list(records)
    return [record for record in records if _resolved_component_ref(record) not in rejected_refs]


def _rejected_shortlist_component_refs(work_root: Path) -> frozenset[str]:
    shortlist_path = Path(work_root) / "shortlist.json"
    if not shortlist_path.exists():
        return frozenset()
    document = store.read_shortlist(work_root)
    raw_items = document.get("items", [])
    if not isinstance(raw_items, list):
        return frozenset()
    return frozenset(
        str(item["component_ref"])
        for item in raw_items
        if isinstance(item, dict)
        and item.get("status") == "rejected"
        and isinstance(item.get("component_ref"), str)
    )


def _resolved_component_ref(record: dict[str, Any]) -> str:
    return f"{record['name']}|{_normalized_spdx(record.get('spdx_id'))}"


def _active_report_repo_refs(work_root: Path) -> tuple[str, ...] | None:
    """Return approved discover refs when the work root has review artifacts."""

    root = Path(work_root)
    if not (root / "discovered.json").exists() or not (root / "repos.candidate.md").exists():
        return None
    return load_discover_approved_repo_refs(root)


def select_main_report_rows(
    work_root: Path,
    config: Config | None = None,
) -> tuple[list[DisclosureRow], list[str]]:
    """Return the exact main-report rows that final presentation output consumes."""

    split, file_gaps = _split_report_records(Path(work_root), config)
    return aggregate_rows(split.main_records), file_gaps


def _split_report_records(work_root: Path, config: Config | None):
    selection = report_selection_from_config(config)
    category_index = build_category_index(_read_discovered_or_empty(work_root))
    default_category = _default_category(config)
    records, file_gaps = collect_resolved_records(work_root, _active_report_repo_refs(work_root))
    records = _exclude_rejected_shortlist_records(work_root, records)
    split = route_occurrences(records, category_index, selection.include, default_category)
    return split, file_gaps


def aggregate_rows(records: Iterable[dict[str, Any] | RoutedRecord]) -> list[DisclosureRow]:
    """Deduplicate records by ``(name, spdx_id or UNKNOWN)`` and aggregate fields."""

    groups: dict[tuple[str, str], _DisclosureAccumulator] = {}
    for raw_record in records:
        record, extra_gaps = _record_and_extra_gaps(raw_record)
        name = str(record["name"])
        spdx_id = _normalized_spdx(record.get("spdx_id"))
        key = (name, spdx_id)
        group = groups.setdefault(key, _DisclosureAccumulator(name=name, spdx_id=spdx_id))
        if spdx_id == _UNKNOWN:
            group.coverage_gaps.add("missing_spdx_id")

        version = _version_display(record)
        group.versions.add(version)
        if version == "unknown":
            group.coverage_gaps.add("missing_version")
        group.found_in.add(str(record["repo"]))
        group.modified.add(_modified_value(record["modified"]))
        description = brief_description(record.get("description"))
        if description is not None:
            group.descriptions.add(description)

        evidence = _object_mapping(record["evidence"], "evidence")
        group.evidence_source_layers.add(str(evidence["source_layer"]))
        source_url = _optional_text(evidence.get("url"))
        if source_url is None:
            group.coverage_gaps.add("missing_source_url")
            package_url = _optional_text(record.get("purl"))
            if package_url is not None:
                group.source_urls.add(package_url)
        else:
            group.source_urls.add(source_url)

        tags = _object_mapping(record["tags"], "tags")
        group.origins.add(str(tags["origin"]))
        group.scopes.add(str(tags["scope"]))
        group.distributions.add(str(tags["distribution"]))
        group.coverage_gaps.update(extra_gaps)

    return sorted(
        (group.to_row() for group in groups.values()),
        key=lambda row: (row.name.casefold(), row.spdx_id.casefold(), row.name, row.spdx_id),
    )


def render_csv(rows: Sequence[DisclosureRow]) -> str:
    """Render report rows as neutralized CSV."""

    csv_rows: list[tuple[object, ...]] = [COLUMNS]
    csv_rows.extend(
        (
            row.name,
            row.spdx_id,
            _join(row.versions),
            _join(row.source_urls),
            _join(row.modified),
            _join(row.origins),
            _join(row.scopes),
            _join(row.distributions),
            _join(row.found_in),
            _join(row.evidence_source_layers),
            _coverage(row.coverage_gaps),
        )
        for row in rows
    )
    return serialize_csv_rows(csv_rows)


def render_markdown(
    rows: Sequence[DisclosureRow],
    file_gaps: Sequence[str],
    *,
    title: str = "RepoLens Main Report",
) -> str:
    """Render report rows as sanitized Markdown."""

    lines = [
        f"# {title.replace(chr(10), ' ')}",
        "",
        "| " + " | ".join(_markdown_table_cell(column) for column in COLUMNS) + " |",
        "| " + " | ".join("---" for _ in COLUMNS) + " |",
    ]

    for row in rows:
        lines.append(
            "| "
            + " | ".join(
                (
                    _markdown_table_cell(render_code_span(row.name)),
                    _markdown_table_cell(row.spdx_id),
                    _markdown_table_cell(_join(row.versions)),
                    _markdown_table_cell(_markdown_source_urls(row.source_urls)),
                    _markdown_table_cell(_join(row.modified)),
                    _markdown_table_cell(_join(row.origins)),
                    _markdown_table_cell(_join(row.scopes)),
                    _markdown_table_cell(_join(row.distributions)),
                    _markdown_table_cell(_join(row.found_in)),
                    _markdown_table_cell(_join(row.evidence_source_layers)),
                    _markdown_table_cell(_coverage(row.coverage_gaps)),
                )
            )
            + " |"
        )

    if file_gaps:
        lines.extend(["", "## Coverage Gaps", ""])
        lines.extend(f"- {render_code_span(gap)}" for gap in file_gaps)

    return sanitize_markdown("\n".join(lines) + "\n")


def render_html(
    rows: Sequence[DisclosureRow],
    file_gaps: Sequence[str],
    *,
    title: str = "RepoLens Main Report",
) -> str:
    """Render report rows as a self-contained, print-landscape HTML artifact."""

    safe_title = _html_text(title.replace("\n", " "))
    colgroup = "".join(f'<col style="width: {width}%">' for width in _HTML_COLUMN_WIDTHS)
    header_cells = "".join(f'<th scope="col">{_html_text(column)}</th>' for column in COLUMNS)
    body_rows = [
        "<tr>"
        + "".join(
            (
                f'<td class="col-name"><code>{_html_text(row.name)}</code></td>',
                f"<td>{_html_text(row.spdx_id)}</td>",
                f"<td>{_html_text(_join(row.versions))}</td>",
                f'<td class="col-source">{_html_source_urls(row.source_urls)}</td>',
                f"<td>{_html_text(_join(row.modified))}</td>",
                f"<td>{_html_text(_join(row.origins))}</td>",
                f"<td>{_html_text(_join(row.scopes))}</td>",
                f"<td>{_html_text(_join(row.distributions))}</td>",
                f"<td>{_html_text(_join(row.found_in))}</td>",
                f"<td>{_html_text(_join(row.evidence_source_layers))}</td>",
                f"<td>{_html_text(_coverage(row.coverage_gaps))}</td>",
            )
        )
        + "</tr>"
        for row in rows
    ]
    if not body_rows:
        body_rows.append(f'<tr><td colspan="{len(COLUMNS)}">No report rows.</td></tr>')

    coverage_section = ""
    if file_gaps:
        gap_items = "".join(f"<li><code>{_html_text(gap)}</code></li>" for gap in file_gaps)
        coverage_section = (
            f'<section class="coverage-gaps"><h2>Coverage Gaps</h2><ul>{gap_items}</ul></section>'
        )

    return (
        "<!doctype html>\n"
        '<html lang="en">\n'
        "<head>\n"
        '<meta charset="utf-8">\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
        f"<title>{safe_title}</title>\n"
        "<style>\n"
        ":root { color-scheme: light; }\n"
        "@page { size: letter landscape; margin: 0.35in; }\n"
        "body { margin: 24px; font: 14px/1.4 Arial, Helvetica, sans-serif; color: #111827; }\n"
        "h1 { margin: 0 0 16px; font-size: 24px; line-height: 1.2; }\n"
        "h2 { margin: 24px 0 8px; font-size: 16px; }\n"
        ".table-wrap { width: 100%; border: 1px solid #d1d5db; }\n"
        "table { border-collapse: collapse; table-layout: fixed; width: 100%; }\n"
        "th, td { border: 1px solid #d1d5db; padding: 6px 8px; "
        "vertical-align: top; text-align: left; }\n"
        "th { position: sticky; top: 0; background: #f3f4f6; font-weight: 700; }\n"
        "td { overflow-wrap: anywhere; word-break: break-word; }\n"
        "code { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; "
        "font-size: 0.92em; }\n"
        "a { color: #0f4c81; text-decoration: underline; }\n"
        ".coverage-gaps ul { margin-top: 8px; padding-left: 22px; }\n"
        "@media print {\n"
        "  body { margin: 0; font-size: 8pt; }\n"
        "  h1 { font-size: 16pt; }\n"
        "  .table-wrap { border: 0; }\n"
        "  table { width: 100%; }\n"
        "  th, td { padding: 3pt 4pt; }\n"
        "  th { position: static; }\n"
        "}\n"
        "</style>\n"
        "</head>\n"
        "<body>\n"
        f"<h1>{safe_title}</h1>\n"
        '<div class="table-wrap"><table>\n'
        f"{colgroup}\n"
        f"<thead><tr>{header_cells}</tr></thead>\n"
        f"<tbody>{''.join(body_rows)}</tbody>\n"
        "</table></div>\n"
        f"{coverage_section}\n"
        "</body>\n"
        "</html>\n"
    )


def _object_mapping(value: object, field_name: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise InputError(f"resolved record {field_name} must be an object")
    return value


def _normalized_spdx(value: object) -> str:
    text = "" if value is None else str(value).strip()
    return text or _UNKNOWN


def _optional_text(value: object) -> str | None:
    if value is None:
        return None
    text = str(value).strip()
    return text or None


def _modified_value(value: object) -> str:
    if value is True:
        return "true"
    if value is False:
        return "false"
    return str(value)


def _version_display(record: dict[str, Any]) -> str:
    version = str(record["version"])
    if version == "unknown" and record.get("declared_version_status") == DECLARED_UNPINNED_STATUS:
        return DECLARED_UNPINNED_STATUS
    return version


def _sorted_values(values: Iterable[str]) -> tuple[str, ...]:
    return tuple(sorted(values, key=lambda value: (value.casefold(), value)))


def _join(values: Sequence[str]) -> str:
    return "; ".join(values)


def _coverage(gaps: Sequence[str]) -> str:
    return _join(gaps) if gaps else _NONE


def _coverage_gap_counts(
    rows: Sequence[DisclosureRow],
    file_gaps: Sequence[str] = (),
) -> tuple[tuple[str, int], ...]:
    counter: Counter[str] = Counter()
    for row in rows:
        counter.update(row.coverage_gaps)
    counter.update(file_gaps)
    return tuple(sorted(counter.items(), key=lambda item: (item[0].casefold(), item[0])))


def _markdown_source_urls(source_urls: Sequence[str]) -> str:
    return "; ".join(markdown_link(url, url) for url in source_urls)


def _markdown_table_cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def _html_source_urls(source_urls: Sequence[str]) -> str:
    return "; ".join(_html_link(url) for url in source_urls)


def _html_link(url: str) -> str:
    label = _html_text(url)
    if not _safe_html_url(url):
        return _html_inert_url_text(url)
    href = html_escape(url, quote=True)
    return f'<a href="{href}" rel="noopener noreferrer">{label}</a>'


def _safe_html_url(url: str) -> bool:
    stripped = url.strip()
    if not stripped:
        return False
    try:
        parsed = urlparse(stripped)
    except ValueError:
        return False
    return parsed.scheme.lower() in {"http", "https", "mailto"}


def _html_inert_url_text(url: str) -> str:
    label = _html_text(url)
    try:
        parsed = urlparse(url.strip())
    except ValueError:
        return label
    if parsed.scheme:
        colon_index = label.find(":")
        if colon_index != -1:
            return f"{label[:colon_index]}&#58;{label[colon_index + 1 :]}"
    return label


def _html_text(value: object) -> str:
    text = "" if value is None else str(value)
    return html_escape(text.replace("\n", " "), quote=False)


def _record_and_extra_gaps(
    raw_record: dict[str, Any] | RoutedRecord,
) -> tuple[dict[str, Any], tuple[str, ...]]:
    if isinstance(raw_record, RoutedRecord):
        return raw_record.record, raw_record.extra_coverage_gaps
    return raw_record, ()


def _read_discovered_or_empty(work_root: Path) -> dict[str, object]:
    path = Path(work_root) / "discovered.json"
    if not path.exists():
        return {"repositories": []}
    value = store.load_json_capped(path, max_bytes=max_bytes_for("discovered"))
    if not isinstance(value, dict):
        raise InputError("discovered.json must be an object")
    return value


def _default_category(config: Config | None) -> str:
    if config is None:
        return DEFAULT_CATEGORY
    discover = config.values.get("discover", {})
    if discover is None:
        return DEFAULT_CATEGORY
    if not isinstance(discover, dict):
        raise InputError("config discover must be an object")
    taxonomy = discover.get("taxonomy", {})
    if taxonomy is None:
        return DEFAULT_CATEGORY
    if not isinstance(taxonomy, dict):
        raise InputError("config discover.taxonomy must be an object")
    raw_default = taxonomy.get("default_category")
    if raw_default is None:
        return DEFAULT_CATEGORY
    if not isinstance(raw_default, str) or not raw_default.strip():
        raise InputError("config discover.taxonomy.default_category must be a non-empty string")
    return raw_default.strip()


def _path_sort_key(path: Path) -> tuple[str, str]:
    text = path.as_posix()
    return (text.casefold(), text)
